name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: EdricChan03/action-build-deploy-ghpages@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        gh-pages-token: ${{ secrets.GH_PAGES_TOKEN }}
